// Code generated by the Lingua Franca compiler from:
// file://home/linguafranca/lf-workspace/teste1/src/HelloWorld.lf
#define LOG_LEVEL 2

#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-o", "30", "sec" };
void lf_set_default_command_line_options() {
        default_argc = 4;
        default_argv = _lf_default_argv;
}
#include "_mqttsubscriber.h"
#include "_messagegenerator.h"
#include "_printmessage.h"
#include "_helloworld_main.h"
typedef enum {
    helloworld_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&envs[helloworld_main],"HelloWorld",helloworld_main,_lf_number_of_workers,1,1,1,0,3,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _helloworld_main_main_self_t* helloworld_main_self[1];
    SUPPRESS_UNUSED_WARNING(helloworld_main_self);
    _mqttsubscriber_self_t* helloworld_sub_self[1];
    SUPPRESS_UNUSED_WARNING(helloworld_sub_self);
    _messagegenerator_self_t* helloworld_msg_self[1];
    SUPPRESS_UNUSED_WARNING(helloworld_msg_self);
    _printmessage_self_t* helloworld_mos_self[1];
    SUPPRESS_UNUSED_WARNING(helloworld_mos_self);
    // ***** Start initializing HelloWorld of class HelloWorld
    helloworld_main_self[0] = new__helloworld_main();
    helloworld_main_self[0]->base.environment = &envs[helloworld_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    
    {
        _helloworld_main_main_self_t *self = helloworld_main_self[0];
        // ***** Start initializing HelloWorld.sub of class MQTTSubscriber
        helloworld_sub_self[0] = new__mqttsubscriber();
        helloworld_sub_self[0]->base.environment = &envs[helloworld_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        helloworld_sub_self[0]->topic = "test/test1";
        helloworld_sub_self[0]->address = "tcp://localhost:1883";
        // width of -2 indicates that it is not a multiport.
        helloworld_sub_self[0]->_lf_message_width = -2;
        envs[helloworld_main].startup_reactions[startup_reaction_count[helloworld_main]++] = &helloworld_sub_self[0]->_lf__reaction_0;
        envs[helloworld_main].shutdown_reactions[shutdown_reaction_count[helloworld_main]++] = &helloworld_sub_self[0]->_lf__reaction_2;
        { // For scoping
            static MQTTClient _initial = NULL;
            helloworld_sub_self[0]->client = _initial;
        } // End scoping.
        { // For scoping
            static char* _initial = "ClientID";
            helloworld_sub_self[0]->clientID = _initial;
        } // End scoping.
        { // For scoping
            static MQTTSub_info _initial = {NULL};
            helloworld_sub_self[0]->info = _initial;
        } // End scoping.
        // Initializing action HelloWorld.sub.act
        helloworld_sub_self[0]->_lf__act.offset = 0;
        helloworld_sub_self[0]->_lf__act.period = -1;
        helloworld_sub_self[0]->_lf__act.last_tag = NEVER_TAG;
        helloworld_sub_self[0]->_lf__act.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(helloworld_sub_self[0]->_lf__act),
        sizeof(char));
        helloworld_sub_self[0]->_lf__act.status = absent;
        helloworld_sub_self[0]->_lf__reaction_0.deadline = NEVER;
        helloworld_sub_self[0]->_lf__reaction_1.deadline = NEVER;
        helloworld_sub_self[0]->_lf__reaction_2.deadline = NEVER;
        //***** End initializing HelloWorld.sub
    }
    {
        _helloworld_main_main_self_t *self = helloworld_main_self[0];
        // ***** Start initializing HelloWorld.msg of class MessageGenerator
        helloworld_msg_self[0] = new__messagegenerator();
        helloworld_msg_self[0]->base.environment = &envs[helloworld_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        helloworld_msg_self[0]->root = "Test Message";
        helloworld_msg_self[0]->period = SEC(1);
        // width of -2 indicates that it is not a multiport.
        helloworld_msg_self[0]->_lf_message_width = -2;
        { // For scoping
            static int _initial = 1;
            helloworld_msg_self[0]->count = _initial;
        } // End scoping.
        // Initiaizing timer HelloWorld.msg.t.
        helloworld_msg_self[0]->_lf__t.offset = SEC(1);
        helloworld_msg_self[0]->_lf__t.period = SEC(1);
        // Associate timer with the environment of its parent
        envs[helloworld_main].timer_triggers[timer_triggers_count[helloworld_main]++] = &helloworld_msg_self[0]->_lf__t;
        helloworld_msg_self[0]->_lf__t.mode = NULL;
    
        helloworld_msg_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing HelloWorld.msg
    }
    {
        _helloworld_main_main_self_t *self = helloworld_main_self[0];
        // ***** Start initializing HelloWorld.mos of class PrintMessage
        helloworld_mos_self[0] = new__printmessage();
        helloworld_mos_self[0]->base.environment = &envs[helloworld_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        helloworld_mos_self[0]->_lf_message_width = -2;
    
        helloworld_mos_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing HelloWorld.mos
    }
    //***** End initializing HelloWorld
    // **** Start deferred initialize for HelloWorld
    {
    
    
    
        // **** Start deferred initialize for HelloWorld.sub
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of HelloWorld.sub.
            helloworld_sub_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of HelloWorld.sub
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of HelloWorld.sub.
            helloworld_sub_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            helloworld_sub_self[0]->_lf__reaction_1.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &helloworld_sub_self[0]->base.allocations);
            helloworld_sub_self[0]->_lf__reaction_1.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &helloworld_sub_self[0]->base.allocations);
            helloworld_sub_self[0]->_lf__reaction_1.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &helloworld_sub_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    helloworld_sub_self[0]->_lf__reaction_1.output_produced[count++] = &helloworld_sub_self[0]->_lf_message.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of HelloWorld.sub
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of HelloWorld.sub.
            helloworld_sub_self[0]->_lf__reaction_2.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 2 of HelloWorld.sub
            _lf_initialize_template((token_template_t*)
                    &(helloworld_sub_self[0]->_lf_message),
            sizeof(char));
        }
        // **** End of deferred initialize for HelloWorld.sub
        // **** Start deferred initialize for HelloWorld.msg
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of HelloWorld.msg.
            helloworld_msg_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            helloworld_msg_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &helloworld_msg_self[0]->base.allocations);
            helloworld_msg_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &helloworld_msg_self[0]->base.allocations);
            helloworld_msg_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &helloworld_msg_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    helloworld_msg_self[0]->_lf__reaction_0.output_produced[count++] = &helloworld_msg_self[0]->_lf_message.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of HelloWorld.msg
            _lf_initialize_template((token_template_t*)
                    &(helloworld_msg_self[0]->_lf_message),
            sizeof(char));
        }
        // **** End of deferred initialize for HelloWorld.msg
        // **** Start deferred initialize for HelloWorld.mos
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of HelloWorld.mos.
            helloworld_mos_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of HelloWorld.mos
        
        }
        // **** End of deferred initialize for HelloWorld.mos
    }
    // **** End of deferred initialize for HelloWorld
    // **** Start non-nested deferred initialize for HelloWorld
    {
    
    
    
        // **** Start non-nested deferred initialize for HelloWorld.sub
        {
        
            // For reference counting, set num_destinations for port HelloWorld.sub.message.
            // Iterate over range HelloWorld.sub.message(0,1)->[HelloWorld.mos.message(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                helloworld_sub_self[src_runtime]->_lf_message._base.num_destinations = 1;
                helloworld_sub_self[src_runtime]->_lf_message._base.source_reactor = (self_base_t*)helloworld_sub_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range HelloWorld.sub.message(0,1)->[HelloWorld.mos.message(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of HelloWorld.sub triggers 1 downstream reactions
                    // through port HelloWorld.sub.message.
                    helloworld_sub_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of HelloWorld.sub, allocate an
                    // array of trigger pointers for downstream reactions through port HelloWorld.sub.message
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &helloworld_sub_self[src_runtime]->base.allocations); 
                    helloworld_sub_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges HelloWorld.sub.message(0,1)->[HelloWorld.mos.message(0,1)] and HelloWorld.mos.message(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range HelloWorld.mos.message(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port HelloWorld.mos.message's trigger struct.
                        helloworld_sub_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &helloworld_mos_self[dst_runtime]->_lf__message;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for HelloWorld.sub
        // **** Start non-nested deferred initialize for HelloWorld.msg
        {
        
            for (int index486184027c8990b = 0; index486184027c8990b < 1; index486184027c8990b++) { helloworld_msg_self[0]->_lf_message._base.source_reactor = (self_base_t*)helloworld_msg_self[0]; }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            }
        
        }
        // **** End of non-nested deferred initialize for HelloWorld.msg
        // **** Start non-nested deferred initialize for HelloWorld.mos
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for HelloWorld.mos
    }
    // **** End of non-nested deferred initialize for HelloWorld
    // Connect inputs and outputs for reactor HelloWorld.
    // Connect inputs and outputs for reactor HelloWorld.sub.
    // Connect HelloWorld.sub.message(0,1)->[HelloWorld.mos.message(0,1)] to port HelloWorld.mos.message(0,1)
    // Iterate over ranges HelloWorld.sub.message(0,1)->[HelloWorld.mos.message(0,1)] and HelloWorld.mos.message(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range HelloWorld.mos.message(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            helloworld_mos_self[dst_runtime]->_lf_message = (_printmessage_message_t*)&helloworld_sub_self[src_runtime]->_lf_message;
        }
    }
    // Connect inputs and outputs for reactor HelloWorld.msg.
    
    // Connect inputs and outputs for reactor HelloWorld.mos.
    {
        {
            // Add action HelloWorld.sub.act to array of is_present fields.
            envs[helloworld_main].is_present_fields[0] 
                    = &helloworld_sub_self[0]->_lf_act.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add action HelloWorld.sub.act to array of intended_tag fields.
            envs[helloworld_main]._lf_intended_tag_fields[0] 
                    = &helloworld_sub_self[0]->_lf_act.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
        }
    }
    {
    }
    {
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port HelloWorld.sub.message to array of is_present fields.
            envs[helloworld_main].is_present_fields[1 + count] = &helloworld_sub_self[0]->_lf_message.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port HelloWorld.sub.message to array of intended_tag fields.
            envs[helloworld_main]._lf_intended_tag_fields[1 + count] = &helloworld_sub_self[0]->_lf_message.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port HelloWorld.msg.message to array of is_present fields.
            envs[helloworld_main].is_present_fields[2 + count] = &helloworld_msg_self[0]->_lf_message.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port HelloWorld.msg.message to array of intended_tag fields.
            envs[helloworld_main]._lf_intended_tag_fields[2 + count] = &helloworld_msg_self[0]->_lf_message.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance HelloWorld
    {
    
        // Set reaction priorities for ReactorInstance HelloWorld.sub
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            helloworld_sub_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            helloworld_sub_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 1);
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            helloworld_sub_self[0]->_lf__reaction_2.index = lf_combine_deadline_and_level(9223372036854775807, 2);
        }
    
    
        // Set reaction priorities for ReactorInstance HelloWorld.msg
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            helloworld_msg_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
        }
    
    
        // Set reaction priorities for ReactorInstance HelloWorld.mos
        {
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            helloworld_mos_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 2);
        }
    
    }
    
    // Initialize the scheduler
    size_t num_reactions_per_level[3] = 
        {2, 1, 2};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 3};
    lf_sched_init(
        &envs[helloworld_main],
        envs[helloworld_main].num_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
